### ISSUE TITLE
(Beta FW) The + Button (hold) doesn't popup the "Macro Overview" Menu

### ISSUE THREAD

**Issue by peaq** [dekuNukem/duckyPad#120]
In the older FW Version you were able to have a Macro Overview by pressing + long enough. 
With the new Version that's no longer the case, was this change intentional ?

**Comment by dekuNukem** [comment]
Yes this is intentional. I had to free up some space for duckyScript 3 features, so it had to go.

This feature was meant to speed up switching before the [profile autoswitcher](https://github.com/dekuNukem/duckyPad-profile-autoswitcher/blob/master/README.md), but with that out, I feel that it is not that useful anymore.
